name: redrose
base: core24
version: '0.5.22'
summary: Integrated ABC music notation environment
description: |
  Redrose lets you write ABC musical scores in ABC notation and, with
  the help of abcm2ps, can display your score. It can also play the score,
  generate MIDI with or without abc2midi, and print the score.

grade: stable
confinement: strict

parts:
  redrose:
    plugin: cmake
    override-pull: |
      craftctl default
      sed -i.bak -e 's|LIBABC2SMF|ABC2MIDI|g' app/settings.cpp
      sed -i.bak -e 's|DRIVER_ALSA|DRIVER_PULSEAUDIO|g' app/settings.cpp
      sed -i.bak -e 's|Icon=redrose|Icon=/usr/local/share/icons/hicolor/scalable/apps/redrose.svg|g' app/redrose.desktop
      sed -i.bak -e 's|default-GM.sf2|TimGM6mb.sf2|g' app/config.h.in
    override-build: |
      craftctl default
      cp -a ${CRAFT_PART_BUILD}/app/locale ${CRAFT_PART_INSTALL}/usr/local/share/redrose/
      mkdir -p ${CRAFT_PART_INSTALL}/usr/local/share/icons/hicolor/48x48/actions
      cp -a ${CRAFT_PART_INSTALL}/usr/share/icons/gnome/48x48/actions/*.png ${SNAPCRAFT_PART_INSTALL}/usr/local/share/icons/hicolor/48x48/actions/

    build-packages:
      - build-essential
      #- libxcb-xinerama0-dev
      #- libwayland-dev
      - qt6-wayland-dev
      - qt6-base-dev
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - pkg-config
      - libspectre-dev
      - libdrumstick-dev
      - libfluidsynth-dev
      #stage-snaps:
      #- gtk-common-themes
      #- qt-common-themes
    stage-packages:
      - libpaper-utils
      - gnome-icon-theme
      - librsvg2-common
      #- gtk2-engines-pixbuf
      #- shared-mime-info
      - qt6-gtk-platformtheme
      #- fontconfig
      #- fontconfig-config
      - fonts-noto-core
      - fonts-ubuntu
      - fonts-freefont-ttf
      - qt6-wayland
      #- libwayland-client0
      #- libwayland-egl1
      #- libgl1-mesa-dri
      #- libxcb-xinerama0
      #- libpulse0
      - libqt6svg6
      - libqt6printsupport6t64
      - libqt6gui6t64
      - libqt6widgets6t64
      - adwaita-qt6
      #- libgdk-pixbuf2.0-bin
      #- libgdk-pixbuf2.0-common
      #- gir1.2-gdkpixbuf-2.0
      #- libgdk-pixbuf-2.0-0
      #- gnome-themes-extra-data
      #- gnome-accessibility-themes
      #- humanity-icon-theme
      #- hicolor-icon-theme
      #- adwaita-icon-theme
      #- yaru-theme-icon
      #- gnome-icon-theme
      #- gnome-colors-common
      - qt6-translations-l10n
      - libgs10-common
      - libspectre1
      - libdrumstick-file2t64
      - timgm6mb-soundfont
      - libfluidsynth3
      - abcm2ps
      - abcmidi
    source: http://github.com/be1/redrose.git
    source-type: git
    source-tag: 0.5.22

  gpu-2404:
    after: [redrose]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper

apps:
  redrose:
    extensions: [gnome]
    environment:
      #WAYLAND_DISPLAY: ../wayland-0
      #PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native
      #FONTCONFIG_PATH: $SNAP/etc/fonts
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
      #LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio
      GS_LIB: $SNAP/usr/share/ghostscript/10.02.1/Resource/Init
      GS_FONTPATH: $SNAP/usr/share/ghostscript/10.02.1/Resource/Font
    desktop: usr/local/share/applications/redrose.desktop
    command-chain:
      - bin/gpu-2404-wrapper
    command: usr/local/bin/redrose
    plugs:
      - desktop
      - desktop-legacy
      - home
      - audio-playback
      - jack1
      - alsa
      - cups-control

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

layout:
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB
  /etc/papersize:
    bind-file: $SNAP/etc/papersize
  /usr/local/share:
    bind: $SNAP/usr/local/share
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
